### ISSUE TITLE
Move shared utilities to separate repository

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/lockup#1125]
As discussed [here](https://github.com/orgs/sablier-labs/discussions/13).

The task is to move the following logic to a separate `@sablier/solidity-utils` package/ repo (name TBD):

- [x] [Adminable.sol](https://github.com/sablier-labs/v2-core/blob/main/src/abstracts/Adminable.sol)
- [x] [NoDelegateCall.sol](https://github.com/sablier-labs/v2-core/blob/main/src/abstracts/NoDelegateCall.sol)
- [x] [Batch.sol](https://github.com/sablier-labs/flow/blob/staging/src/abstracts/Batch.sol)
- [x] Some portions of [Base.s.sol](https://github.com/sablier-labs/airdrops/blob/main/script/Base.s.sol)
- [x] Some test files inherited by Flow from Lockup

**Comment by PaulRBerg** [comment]
Idea: create an abstract contract that implements the `collectFee` logic that is currently duplicated across the Airdrops and Flow repos.

**Comment by andreivladbrg** [comment]
Similar to your idea, we could also:
1. Add a contract that inherits `ERC721` and implements the `_update` function. (it would require a virtual function `isTransferable`)
2. Declare the `MAX_BROKER_FEE` and `nextStreamId`.

Though I don't have a strong opinion about these, I am not sure where we should draw the line on what to move there or not. 🤔

**Comment by smol-ninja** [comment]
The contracts mentioned in the OP are already abstract contracts. So moving them to the Utilities repo sounded like a good plan. On the other hand, `_update`, `MAX_BROKER_FEE`, and `nextStreamId` are contract-specific functions and variables, and we should keep them where they belong.

`collectFee` technically is a part of admin-related functions, so it makes sense to move it to a new abstract contract, along with other admin-related functions if there are any.

**Comment by andreivladbrg** [comment]
> The contracts mentioned in the OP are already abstract contracts. So moving them to the Utilities repo sounded like a good plan. On the other hand, `_update`, `MAX_BROKER_FEE`, and `nextStreamId` are contract-specific functions and variables, and we should keep them where they belong

I could argue that `_update` function is a part of the abstract `ERC721` contract.  

> `collectFee` technically is a part of admin-related functions, so it makes sense to move it to a new abstract contract, along with other admin-related functions if there are any


the transfer is made to the `admin` address, is not necessarily callable only by him

**Comment by smol-ninja** [comment]
> I could argue that _update function is a part of the abstract ERC721 contract.

Yes it is but so what?

Another argument against it is that it is not necessary that Flow and Lockup will share the same requirements for the implementation of `_update`. For example, see [this discussion](https://github.com/sablier-labs/company-discussions/discussions/59) which would have required a different implementation in Lockup.

The contracts in Utilities should be very generic and should not depend on protocol specific requirements.

> the transfer is made to the admin address, is not necessarily callable only by him

Fair point.

**Comment by andreivladbrg** [comment]
> Another argument against it is that it is not necessary that Flow and Lockup will share the same requirements for the implementation of `_update`. For example, see [this discussion](https://github.com/sablier-labs/company-discussions/discussions/59) which would have required a different implementation in Lockup

good point
