### ISSUE TITLE
Package tethering

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/lockup#808]
As discussed in https://github.com/sablier-labs/company-discussions/discussions/25

- [x] Move all the V2 Periphery contracts to an Airdrops rpeository
- [x] Update all stale references (e.g. turn "V2 Core" into "V2 Lockup")
- [x] Remove the "V2" from the contract names (note: for ASCII, you can use the "Dark with Shadow" font on this [tool](https://textfancy.com/text-art/))
- [x] Don't forget about the related stuff, e.g. the [Wikis](https://github.com/sablier-labs/v2-core/wiki)
- [x] Rename this repo to `lockup`

**Comment by andreivladbrg** [comment]
In advance, I want to mention that this change will likely take a longer amount of time.

**Comment by PaulRBerg** [comment]
Yep. That's why I've marked it as `effort: epic`.

**Comment by andreivladbrg** [comment]
just noticed this:

> Rename this repo to v2-lockup

wasn't the idea to also remove "v2" from the repo name?

from https://github.com/sablier-labs/company-discussions/discussions/25

AVB:
<img width="799" alt="image" src="https://github.com/sablier-labs/v2-core/assets/99738872/f14464e7-c402-458a-9b27-876ea833f126">

PRB: 

<img width="757" alt="image" src="https://github.com/sablier-labs/v2-core/assets/99738872/d4bf4c26-fbf4-47f9-a8b9-570411d94877">

**Comment by PaulRBerg** [comment]
Oh shoot, you're right @andreivladbrg.

The repo should be renamed to `evm-lockup` or `sablier-lockup`.

I would go with the latter, though I'm on the fence about it. Which one do you like more? Cc @smol-ninja.

**Comment by smol-ninja** [comment]
I am more inclined towards calling it `sablier-lockup`. My rationale is that Sablier may not necessarily be compatible with [different types of zkEVMs, such as type 3 and type 4](https://vitalik.eth.limo/general/2022/08/04/zkevm.html) [^1] without modifying some parts of it. Even though they are not in practice yet and not very popular, calling it `evm-lockup` wouldn't do justice to the name.

-------------------

Since this is going to be an epic level of effort and likely to take longer time (as Andrei correctly pointed out), there could be a huge number of conflicts between changes introduced by this and other PRs raised during the same period, should we split it into multiple issues for a smooth transition from current architecture to PacTet architecture?

[^1]: zkEVMs are also EVMs.

**Comment by smol-ninja** [comment]
Fair point about `evm-lockup`. I agree with both of your arguments. 

> I am open to that, but I would still prefer to keep this "parent" issue to track all the other "child" issues. We could replace the task list in the OP with references to the other issues.

Yes, thats what I had in my mind. We can split into the following sub-issues (suggestions welcome):

- Move all the V2 Periphery contracts here and integrate with the core repo
- Rename this repo to `evm-lockup` and refactor the contract names
  - Update all references in the code such as function names, variables etc.
  - Update markdown guidelines
- Update Wikis
- Update Sablier docs

@andreivladbrg do you have any comment on this?

**Comment by PaulRBerg** [comment]
@smol-ninja sounds good.

**Comment by andreivladbrg** [comment]
>Move all the V2 Periphery contracts here and integrate with the core repo
Rename this repo to evm-lockup and refactor the contract names
    Update all references in the code such as function names, variables etc.
    Update markdown guidelines

between these two, we should remove "V2" from the contracts

one other thing bad with the `sablier-lockup` name is that it would be redundant to have "sablier" twice in the github URL: `sablier-labs/sablier-lockup`

**Comment by PaulRBerg** [comment]
> we should remove "V2" from the contracts

yeah, that should be another issue

> one other thing bad with the sablier-lockup name is that it would be redundant to have "sablier" twice in the github URL: sablier-labs/sablier-lockup

That's not bad, actually. The name "sablier" would appear on more computers.

**Comment by smol-ninja** [comment]
As discussed on Slack, this will be picked after [major refactoring](https://github.com/sablier-labs/v2-core/discussions/805) and [LockupTranched](https://github.com/sablier-labs/v2-core/issues/787) contracts are finished.

**Comment by PaulRBerg** [comment]
Another implication of PacTet is that we will have to update the name of our NFT collections on Etherscan.

For instance, [this collection](https://etherscan.io/token/0xb10daee1fcf62243ae27776d7a92d39dc8740f95) should be renamed from "Sablier V2 Lockup Linear NFT" to "Sablier Lockup Linear v1.0.1 NFT".

**Comment by smol-ninja** [comment]
The name is not related to Etherscan. It's ERC721 metadata set up [in our core contracts](https://github.com/sablier-labs/v2-core/blob/2b65c464a40fe0924ef1c3ce0aa24a0d90b3abf8/src/SablierV2LockupLinear.sol#L65).

**Comment by PaulRBerg** [comment]
> The name is not related to Etherscan

Actually, it's _also_ related to Etherscan. The NFT collection has to be manually listed (which is what I did a while ago).

but yes you're right that we also have to update the metadata in the Solidity code.

**Comment by smol-ninja** [comment]
Original issue https://github.com/sablier-labs/v2-core/issues/820.

The task is to adjust the description generated in the NFT descriptor to account for the package tethering, i.e., say LockupLinear v1.1.2 instead of Sablier V2:

https://github.com/sablier-labs/v2-core/blob/d5aea835dfe32b6cffa1c8cb40a7ba458f4ab5ee/src/SablierV2NFTDescriptor.sol#L261-L279

**Comment by smol-ninja** [comment]
Since `open-ended` and `core` are going to share the same periphery contracts, shouldn't we include open-ended repo into this as well? Ofc, we can choose to not include it but what are your thoughts on this?

**Comment by smol-ninja** [comment]
Yes thats what I meant, or we build separate periphery contracts for the `open-ended`, i.e. `v2-lockup` contains core and periphery required for lockup product and open-ended repo contains core and periphery required for open-ended.

**Comment by PaulRBerg** [comment]
Got it.

I need to review `open-ended` before I am able to properly comment on this. But my instinct is to keep them separated.

**Comment by andreivladbrg** [comment]
> Since open-ended and core are going to share the same periphery contracts, shouldn't we include open-ended repo into this as well? Ofc, we can choose to not include it but what are your thoughts on this?

this is not correct, this is why we have renamed the batch contract to [BatchLockup](https://github.com/sablier-labs/v2-periphery/pull/322)

**Comment by smol-ninja** [comment]
> i am not in favor of this

Me neither. I also think we should keep OE separate from lockup repo.

**Comment by smol-ninja** [comment]
@PaulRBerg should we rename `SablierNFTDescriptor` to `LockupNFTDescriptor` or `SablierLockupNFTDescriptor` given that NFT Descriptor for Flow would be separate?

**Comment by PaulRBerg** [comment]
The jury is still out if it will be separate. But let's go with `LockupNFTDescriptor` for now.

**Comment by smol-ninja** [comment]
The refactor PR has been merged so now we can move ahead with changing the repo name.

**Comment by andreivladbrg** [comment]
> The [refactor PR](https://github.com/sablier-labs/v2-core/pull/994) has been merged so now we can move ahead with changing the repo name.

wait, i think we shouldn't rename it until `staging` is merged to `main` - i.e. when we release the next version

**Comment by smol-ninja** [comment]
I understand your point—it would be odd to have two repos tied to the current release: `lockup` and `v2-periphery`.

While writing this, I thought, what if we archive both `v2-core` and `v2-periphery` as they are, and then fork `v2-core` (including all branches) into a new `lockup` repo? What do you think?

**Comment by andreivladbrg** [comment]
> I understand your point—it would be odd to have two repos tied to the current release: `lockup` and `v2-periphery`.
> 
> While writing this, I thought, what if we archive both `v2-core` and `v2-periphery` as they are, and then fork `v2-core` (including all branches) into a new `lockup` repo? What do you think?

hmm, that's an idea, not sure yet what to say

the point is to not rush with the decision

**Comment by PaulRBerg** [comment]
I suggest renaming this repo to `lockup` instead of creating a separate one. The rationale is thus:

- We would lose the 310+ stars
- We would lose the connectivity enabled by the historical backlinks (on X, Telegram, etc.)

**Comment by smol-ninja** [comment]
I have updated the Wiki, there were some commands that no longer apply such as related to `createWithRange`.

https://github.com/sablier-labs/lockup/wiki

**Comment by smol-ninja** [comment]
Now, I think we can close this issue.

**Comment by andreivladbrg** [comment]
Yeahh, lesgoo, long way, but we are here 🚀
